name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: set -e; for day in day*; do if [ -f "$day/Cargo.toml" ]; then cargo build --manifest-path $day/Cargo.toml --verbose; fi; done
    - name: Run tests
      run: set -e; for day in day*; do if [ -f "$day/Cargo.toml" ]; then cargo test --manifest-path $day/Cargo.toml --verbose; fi; done
